### ISSUE TITLE
[Newsfeed]ошибка воспроизведения видео и превью

### ISSUE THREAD

**Issue by baktiyarmoldoev** [dwayned84/home#13]
Проверял на production
Браузер Chrome v.96.0.4664.45
Android 10 OS MIUI 12.0.6.0

Пререквезиты:
Пользователь залогинен как: demo/demo
Пользователь находится на странице newsfeed

Шаги воспроизведения

Пролистать ленту
Нажать на видео в ленте

Ожидаемый результат: в ленте должно воспроизводится превью видео.
При нажатии на видео должно воспроизводится видео

Фактический результат: в ленте не воспроизводится превью к видео.
При нажатии на видео появляется ошибка "this video unavailable"

![Screenshot_2021-11-27-23-56-44-470_com android chrome](https://user-images.githubusercontent.com/95124232/143691779-2d846a17-3001-4efc-bbe9-7743221fc923.jpg)
![Screenshot_2021-11-27-23-57-02-610_com android chrome](https://user-images.githubusercontent.com/95124232/143691793-982e1283-f635-4253-ba19-6f5098c70813.jpg)

**Comment by dwayned84** [comment]
Проверял на production
Браузер Chrome v.96.0.4664.45
Android 10 OS MIUI 12.0.6.0

Пререквезиты:
Пользователь залогинен как: demo/demo
Пользователь находится на странице newsfeed

Шаги воспроизведения

Пролистать ленту
Нажать на видео в ленте

Ожидаемый результат: в ленте должно воспроизводится превью видео.
Фактический результат: в ленте воспроизводится превью видео.

Работает как Ожидается. Отправляю на UAT

**Comment by dwayned84** [comment]
Проверил. Работает как ожидается
