### ISSUE TITLE
[Мобильная версия ]ошибка открывания view all photos 

### ISSUE THREAD

**Issue by Daniyar1988** [dwayned84/home#15]
проверял на смартфоне Xiami8 Mi play A9
версия приложения : chrome 94.0.4606.71
операционная система: android 11;sm-a525f build/rp1a.200720.012

пререквизиты:
пользователь залогинен как demo/demo
пользователь находится на странице просмотра фотографий друзей

шаги воспроизведения:
Тэп на ссылку меню My Guests
Тэп на любого пользователя из списка
листаем фотографии друга  до появления "view all photos"
нажимаем на ссылку "view all photos"

ожидаемый результат:
увидеть все фотографии на экране
фактический результат
открывает последнее фото в низком качеств

https://user-images.githubusercontent.com/95124344/143732862-7a2c88e1-6383-45cf-9f6d-e49d8858fc05.mp4

е

**Comment by dwayned84** [comment]
Invalid defect
